[package]
name = "zksync_eth_sender"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_eth_client = { path = "../../lib/eth_client", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }

zksync_basic_types = { path = "../../lib/basic_types", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
web3 = "0.18.0"
metrics = "0.17"
vlog = { path = "../../lib/vlog", version = "1.0" }

tokio = { version = "1", features = ["full"] }

num = { version = "0.3.1", features = ["serde"] }
anyhow = "1.0"
async-trait = "0.1.31"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4.0"
